ffbb_listes:
    path:     /
    defaults: { _controller: FfbbBundle:Listes:index }

ffbb_table:
    path:     /listes-participants
#    defaults: { _controller: FfbbBundle:Groupe:index }
    defaults: { _controller: FfbbBundle:Groupe:afficherParticipants }


ffbb_homepage:
    path:     /villes
    defaults: { _controller: FfbbBundle:Default:index }

ffbb_villes_groupe:
    path:     /villes/{idGroupe}
    defaults: { _controller: FfbbBundle:Default:groupe }

ffbb_supprimer_groupe:
    path:    /supprimer-groupe/{idGroupe}
    defaults: { _controller: FfbbBundle:Groupe:delete }

ffbb_renommer_groupe:
    path:    /renommer-groupe/{idGroupe}
    defaults: { _controller: FfbbBundle:Groupe:renommer }

ffbb_update_groupe:
    path:    /update-groupe/{idGroupe}
    defaults: { _controller: FfbbBundle:Groupe:renommerGroupe }

ffbb_rencontres:
    path:     /rencontres/{idGroupe}
    defaults: { _controller: FfbbBundle:Rencontres:index }

ffbb_competitions:
    path:     /competitions
    defaults: { _controller: FfbbBundle:Competitions:index }

ffbb_rapports:
    path:     /rapports
    defaults: { _controller: FfbbBundle:Rapports:index }

ffbb_barycentre:
    path:     /barycentre/{idGroupe}
    defaults: { _controller: FfbbBundle:Rencontres:barycentre }

ffbb_exclusion:
    path:     /exclusion/{idGroupe}
    defaults: { _controller: FfbbBundle:Rencontres:exclusion }


ffbb_contact:
    path:     /contact
    defaults: { _controller: FfbbBundle:Rencontres:contact }

ffbb_terrain:
    path:     /terrain-neutre/{idGroupe}
    defaults: { _controller: FfbbBundle:Rencontres:terrainNeutre }

ffbb_details_calcul:
    path:     /details-calcul
    defaults: { _controller: FfbbBundle:Rencontres:detailsCalcul }

# routing ajout√© pour la liste de participants et de lieux neutres

ffbb_creer_liste_participants:
    path:     /creer-liste-participants
    defaults: { _controller: FfbbBundle:Listes:creerListeParticipants }

ffbb_creer_liste_lieux:
    path:     /creer-liste-lieux
    defaults: { _controller: FfbbBundle:Listes:creerListeLieux }

ffbb_select_liste_participants:
    path:     /select-liste-participants
    defaults: { _controller: FfbbBundle:Groupe:afficherParticipants  }

ffbb_select_liste_participants2:
    path:     /select-liste-participants
    defaults: { _controller: FfbbBundle:Groupe:afficherParticipants  }
    methods:  [GET]



